[gcp_service_account]
type = "service_account"
project_id = "fcinventory-manager"
private_key_id = "03ed8e4526fa60ce13e7a668bce6d12ef6fd9080"

private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCt6R+bf6Rvdywq
rsvg5WzVOlFsffqitwsKwfk9Xk7wUnuAB9JNFOntHseKQAg71dGKbYw8SRxfBgoh
2yXFSH6K2DMo3x2QfDQZEJqTTCP5o8pfPa1anztoxR+nXjGySNfFUWJ+RxTfU0s6
jKoyC7Sy5wZmHXq5sYA4eb3tRPw1aMUL4MVHIZ2zAS7GyKvvvFQ+MloqxejZbZgs
V3FrfcDZbZAXJiFk4cVeKX2FYX6TqGI3QA5YGiG3We9cfakAHSBKvfvAKWPERXws
ZNetSCkQU0EXOR9SOgfxQ1BrLZpBYRhFPmfcorayNCqqJSO46QBoLJcvhspBVbw7
L5GX1Wi/AgMBAAECggEABMdVf83vrfbPikZOgkBLnHnpwUCeiAuqv5tTRrhpet9v
vU9GgnYcp2m9GeaaIB36XM9kMK17NheeytqQT+3aBeUPvGordpjmS/oE0h9TFCNh
oC3vR+b8/usyH3gBhy1kbThhq6g2wc9ltcomGXhXRfZkwQTDJoivrHcyUAUhP2Zo
Y923FUiTcgL9Ft3Sy45ya9144ew+2IaUC6pKdj/xO8IWp+ocOYjESmWg4b/Ko3Qw
vLsmNsy7s2+wt0NyxgQDde/mh/eEiZjqNNJg7xz1KSUeRGn3Eqog7yX4psh6RlRe
EwCNHKQNI6Jyvg+Yk1BKyQoKv+nM1gIjwdfx5TjoYQKBgQDYTUQMjw2fHsNmHeo+
Md+RYHNYV5mgxn/Fu0qw0LJXK2ZKvWLcaDHbHcqv0W3iCrFTExvGoZoN2JH2pucE
uOXKO9qSF2kwd1YeP7vxUT6wtzYDXjZDP8k1lv5Awu5BE80sGLl88tr8kZL9mY84
bS3Wu+O7qA43JsXN3StjtR0O4wKBgQDN1CYGppzRhDNy33+vZMBGkyf8HF3e/nus
I0T477+Lf9Z6298c5FKDVV1QWauRJ+UQJcACSid4RG0U8t00RrTLfREtoUtxzkON
joYw3cIfy/71oRhtU2+DleebF+F8mmFeyW5FCwz2Gzq2CKIrBjvx3wDI09FKAR6F
g1x3+8vpdQKBgQDBLPBTTwdZTr4v2xOyjBQg38Tj5whbYCwIyeZA14IO+8GVimJa
eevcx1SXhTDfqbEIgo5R7U2KhBqH8DNuMjt3S9E+nA3jrRCKX11YfbjBVj6071UC
5lqqs7lK2Uyzbh3U/hfakYImA1UFjDkuqcNAffk7RTG867HI03fGyp+zBQKBgHbA
Rmwh5moO/uvwvKdB1pkhP7l52ELWyh2Hf7yr/fQK/oCFqFTv+hchwiOgiJbH0KWf
UgdAJ0OBHvouIKePf7HDZ4zO+UsguOLL7un0l5JmzKOEnSY+NCFT9HsLrSGJpFHe
n0sgVAsNrLLnikCOaTlj8vzrEF3FBYn8PvZOhNgdAoGBAL06DZ1Zx3npVy+V/f7g
50imUoGh5iLyy2iikFzYuWdTJQWBDY7d55XQsZKl5aqiM7t7NqHmlYt02HLgInkq
1/0iV8OyMG++vzjllmYuDMsXxAiALoGgIJLkk0ERue7MYzb7od+rXEpmO+5AUZyT
49DAx8A9f+E1LGhHboO4luXB
-----END PRIVATE KEY-----
"""

client_email = "fcinventory-manager@fcinventory-manager.iam.gserviceaccount.com"
client_id = "109252815627874412303"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/fcinventory-manager%40fcinventory-manager.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
